# Generated by Django 4.0.4 on 2022-05-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ord_cost_rub',
            field=models.FloatField(null=True, verbose_name='Стоимость, руб.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ord_cost',
            field=models.FloatField(verbose_name='Стоимость,$'),
        ),
    ]
